apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: dfs-mds-hpa
  namespace: dfs
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: dfs-mds
  minReplicas: 3
  maxReplicas: 30
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80
