apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: dfs
  namespace: dfs
  labels:
    release: prometheus
spec:
  selector:
    matchExpressions:
      - key: app
        operator: In
        values:
          - dfs-mds
          - dfs-monitor
          - dfs-osd
          - dfs-custodian
  endpoints:
    - port: metrics
      interval: 15s
      path: /metrics
  namespaceSelector:
    matchNames:
      - dfs
